## Classification and Regression
These are defined based on type of output metric that is being predicted. If the predicted target data is a discrete, like yes/no, spam/ham etc... its classification else if its continuous like price of house, loss in insurance claim etc. It is regression.

### Learning evaluation metrics based on classification or regression
In classification metrics checked are 

#### Accuracy
number of collectly identfied instance over all instance

In [3]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
scorePerc = accuracy_score(y_true,y_pred)
print scorePerc
accuracy_score(y_true,y_pred,normalize=False)

0.5


2

##### Shortcomings of accuracy:
Accuracy predicts if result is match or not. But there are cases where accuracy is not what we are looking for.


Eg in cancer prediction we may want it to proactively detect cancer even if it gets a few false positives.. hence accuracy might be low with false positives but we ensure it detects cancer
Also in case of skweded distribution accuracy is not the best metric.

#### Precision  and Recall
So In algo there are 3 outcomes Correct, FalsePositive, False Negative.
Correct when predicted == actual state
False positive = when predicted true but is false 
False negative = when predicted false but is true.. (missing this in burglar alarm case is more costly)

Note above can extened beyond binary true and false for more than one classification like predicted A but not A

Precision is how many prediction we got correct from total predictions, CorrectlyPredicted()/Total Predicted()
Recall is how many predictions we got correct from total actuals, CorrectlyPredicted()/ Total Correct Actuals();

Recall takes into account how many misses (False negatives)
Precision takes into account False Positives how correct we are.

Some times we need better recall than Precision and other times vicecersa


In [2]:
from sklearn.metrics import precision_score, recall_score
y_pred = [0, 1, 1, 3]
y_true = [0, 1, 0, 1]
precScore = precision_score(y_true,y_pred,average=None,labels=[0,1])
print precScore  # 0th element is 1 as we predicted 0 cocrreclty out of total pred = 1
#1st element is 0.5 as we predicted 1 correclty once and incorreclty second time.. False positive
recallScore = recall_score(y_true,y_pred,average=None, labels=[0,1])
print recallScore
# both elemnet are 0.5 as total count of 0 and an 1 is 2 and we predicted correclty only once.. 
a_true = ['spam','ham','spam','ham']
a_pred = ['spam','spam','ham','ham']
recall_score(a_true,a_pred,average=None, labels=['spam','ham'])

[ 1.   0.5]
[ 0.5  0.5]


array([ 0.5,  0.5])

In [3]:
from sklearn.metrics import confusion_matrix
confusion_matrix(a_true,a_pred,labels=['spam','ham']) # illustrates the confusion matrix from which we compute precision 
#and recall scores

array([[1, 1],
       [1, 1]])

#### F1Score
The F1 score can be interpreted as a weighted average of the precision and recall, where an F1 score reaches its best value at 1 and worst score at 0. The relative contribution of precision and recall to the F1 score are equal.

F1 = 2 *(precision * recall) / (precision + recall)

In [5]:
from sklearn.metrics import f1_score
f1_score(y_true,y_pred,average=None,labels=[0,1])

array([ 0.66666667,  0.5       ])

In regression metrics checked are 
As mentioned earlier for regression type of problems we are dealing with model that make predictions on continuous data. In this case we care more about how close the prediction is.
For example with height & weight predictions we do not care as much if the model can 100% accurately predict someone's weight down to a less than a fraction of the pound, but perhaps how consistently the model can make a close prediction (perhaps with 3-4 pounds of the individual).

#### Mean Absolute Error
The mean absolute error takes the total absolute error of each example and averages the error based on the number of data points.

#### Mean squared error
Some benefits of squaring the residual error is that it automatically converts all the errors as positives, emphasizes larger errors rather than smaller errors, and from calculus is differentiable which allows us to find the minimum or maximum values.

In [1]:
from sklearn.metrics import mean_absolute_error, median_absolute_error, mean_squared_error
y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
abs_error = mean_absolute_error(y_true,y_pred)
print abs_error
print median_absolute_error(y_true,y_pred)
mean_squared_error(y_true,y_pred)
# not multioutput args can be used when input a composite data array, check mean_absolute_error?

0.5
0.5


0.375

#### R2 Score (Corefficient of Determination)
In statistics, the coefficient of determination, denoted R2 or r2 and pronounced "R squared", is a number that indicates the proportion of the variance in the dependent variable that is predictable from the independent variable.
R2 would range from 1 to -infinity.. closer to 1 the better the prediction

check https://en.wikipedia.org/wiki/Coefficient_of_determination for excelent description of R2.

In breif 
R2 = 1 - (SSres/SStot) 

SStot = variance (sum of square of mean of true values - each true value)

SSres = sums of squres of residue i.e. pred-actual  

In high level R2 score takes into accout of spread of data using SStot and checks the spread of data with respect to predicted data (residue)SSres in proportion to its total => SSres/SStot.

The lower the values of SSres/SStot the more accurate our prediction fits the real value irrespective of existing variance in the data.-- This is the difference from mean sqaure error, where initial variance of data is not considered in evaluating the prediction. Hence r2 score might give better value when our prediction is good but data is spread out hence prediction mean sqaured error is hight.

Note: R2 can be negative when prediction is very bad and actual varaince is low such that SSres/SStot > 1



In [2]:
from sklearn.metrics import r2_score
r2_score(y_true,y_pred)

0.94860813704496794