In [2]:
from sklearn import svm, datasets
import numpy as np
import matplotlib.pyplot as plt


In [11]:
iris = datasets.load_iris()
X = iris.data[:,:2] # takin only the first two dim to be able to plot this in 2D graph
y = iris.target

In [41]:
svc = svm.SVC(kernel='linear', C=1, gamma='auto').fit(X,y)

In [47]:
#learning np.meshgrid
aa,bb = np.meshgrid([1,2,3],[10,20,30])
#this arrages aa as 
aa

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
#and bb as
bb

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [50]:
#hence we can do aa + bb
aa + bb # which contains all combination of a and b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [52]:
bb.ravel() # convert 2d to 1d array index

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [39]:
x_min, x_max = X[:,0].min()-1, X[:,0].max()+1 # min and max range of first dimension
y_min, y_max = X[:,1].min()-1, X[:,1].max()+1 # min and max range of second dimnesion
h = 0.5
xx, yy = np.meshgrid(np.arange(x_min,x_max,h),np.arange(y_min,y_max,h))
xx

array([[ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8],
       [ 3.3,  3.8,  4.3,  4.8,  5.3,  5.8,  6.3,  6.8,  7.3,  7.8,  8.3,
         8.8]])

In [36]:
%matplotlib inline
plt.subplot(1,1,1)
np.c_[xx.ravel(), yy.ravel()] ## xx.ravel() returns all posible c